### ISSUE TITLE
Propose to add events

### ISSUE THREAD

**Issue by VanyaNexus** [Webbeh/WorldGuard-Events#10]
I propose to add events for creating and deleting a region, as well as adding and deleting participants and members from the region. This will help a lot in plugin development.

**Comment by Webbeh** [comment]
Hi.

This is a valid suggestion but I'm afraid I will not be doing much more work with this plugin.

I'm leaving this issue open. If someone else wants to implement it through a pull request, I'll close this issue with that.

In the meantime, feel free to fork this and edit as you wish.
