### ISSUE TITLE
1.19.4 Support

### ISSUE THREAD

**Issue by 0bviouslee** [Webbeh/WorldGuard-Events#11]
Hi there, it seems like as of 1.19.4 this plugin no longer works / triggers. I use https://www.spigotmc.org/resources/conditionalevents-custom-actions-for-certain-events-1-8-1-19-4.82271/ with your plugin and it sadly doesn't trigger the WG events now.

**Comment by Webbeh** [comment]
Hi !

Do you have an error showing ? How is it not working ? Which events are not triggering ?

Which version of WorldGuard are you using ?

I have some time to check tonight, if you have more info it would help lots.

Thank you !

**Comment by 0bviouslee** [comment]
> Hi !
> 
> Do you have an error showing ? How is it not working ? Which events are not triggering ?
> 
> Which version of WorldGuard are you using ?
> 
> I have some time to check tonight, if you have more info it would help lots.
> 
> Thank you !

Hey there! There are no errors, but basically whenever I enter an event or leave an event, the plugin I use uses your plugin to track it, though it no longer triggers when I enter an event (and the author said to contact you). Sorry of this is vague!

I'm using WorldGuard 7.0.8-SNAPSHOT+2235-feb548a and Paper 1.19.4-527

**Comment by Webbeh** [comment]
I'm the author of this plugin. I'll have a look later on today and let you know then.

**Comment by 0bviouslee** [comment]
> I'm the author of this plugin. I'll have a look later on today and let you know then.

Sorry I meant the author of https://www.spigotmc.org/resources/conditionalevents-custom-actions-for-certain-events-1-8-1-19-4.82271/ (ConditionalEvents). They said to contact you as it uses your plugin to track the region the player enters. Thank you!

**Comment by Webbeh** [comment]
Just tested this and everything seems to be working as intended.

WorldEdit  v7.2.15-SNAPSHOT+6413-bd9af40
WorldGuard v7.0.8-SNAPSHOT+2235-feb548aj
WorldGuardEvents v1.18.1
ConditionalEvents v4.24.3

ConditionalEvents config
```yml
Events:
  event0:
    type: wgevents_region_enter
    actions:
      default:
        - "title: 20;40;20;&6&lENTERING AREA;%region%"
```

Proof of it working
https://youtu.be/fIwl32zL_1I

**Comment by 0bviouslee** [comment]
For anyone looking to fix this, change this in your WorldGuard config:

use-player-move-event: false
use-player-teleports: false

to

use-player-move-event: true
use-player-teleports: true

**Comment by Webbeh** [comment]
Glad you found a fix! Indeed, player move events are required by WG region events.
