### ISSUE TITLE
Citizens integration

### ISSUE THREAD

**Issue by aaronpostus** [Webbeh/WorldGuard-Events#12]
I'm using Citizens and I'm trying to use the onRegionEntered event to detect when a citizen enters a region. Is this possible with the current integration of the plugin? At the moment, the event isn't being called when an NPC (player entity) passes into the region... but I really need this to be possible.

**Comment by aaronpostus** [comment]
It recognizes a normal player entering the region just fine, so there is no issue with my code.

**Comment by Webbeh** [comment]
Repo is abandoned and citizens integration was never planned, sorry.
