### ISSUE TITLE
The events aren't triggered

### ISSUE THREAD

**Issue by Jammone** [Webbeh/WorldGuard-Events#6]
Hello, I wrote a very basic plugin using WorldGuardsEvents.
Sadly the event's are never triggered.

is this plugin still workin on minecrat 1.16.5 and WoldGuard 7.0.4?

**Comment by Frostingly** [comment]
I'm having the same issue, seems like the author is dead...

**Comment by Frostingly** [comment]
Alright, I found out why, if you select the region from 1 width, it won't work, you gotta select a region that's wide and tall.

**Comment by Apisathan** [comment]
Am using 1.16.5 and wg 7.0.4 and works fine for me.

**Comment by ofirtim** [comment]
I currently have the same issue,

	@EventHandler
	public void onLeaveRegion(RegionsLeftEvent event) {
		Player e = event.getPlayer();
		Prisoner prisoner = Prisoner.getPrisoner(e);
		@NotNull Set<ProtectedRegion> regions = event.getRegions();
		for (ProtectedRegion region : regions) {
			System.out.println(true);
			if (!prisoner.isPrisoner()) return;
			
			Jail jail = prisoner.getPrisonatingInfo().getKey();
			
			if (!jail.getRegionName().equalsIgnoreCase(region.getId())) return;
			Bukkit.broadcastMessage(Messanger.getMessage(Message.JAILBREAKER_ANNOUNCEMENT));
		}
	}

tried debugging with the sysout true logging, didn't even print at all, this is bugged or something? I am using 1.17 though does it support it?

**Comment by Webbeh** [comment]
The events do trigger as long as WorldGuard is installed and is the correct version.

Your code doesn't make any sense though. You're trying to print "true" to the server's console (, not to "enable debugging". If you want to print something, `Bukkit.getLogger().info("some text");` is your friend... But hey, that's plugin development 101.

Assuming your "prisoner" plugin works, your code could be simplified like so : 

```java
@EventHandler
public void onLeaveRegion(RegionsLeftEvent event) {
    Player e = event.getPlayer();
    Prisoner prisoner = Prisoner.getPrisoner(e);
    if(!prisoner.isPrisoner()) return;
    Jail jail = prisoner.getPrisonatingInfo().getKey();
    if(event.getRegionsNames().contains(jail.getRegionName().toLowerCase())
    {
        Bukkit.broadcastMessage("Jailbreak");
    }
}
```

If this doesn't work at all, you may just simply have forgotten to register the event. Happens to everyone.

**Comment by Webbeh** [comment]
Tested everything. Everything works.
Note that I had to write a little plugin for the "/wgt" command.

https://youtu.be/tS2gzwxAv7s

**Comment by ofirtim** [comment]
Tested it too, apparently it wasn't meant to be shadowjared but I somehow managed to shadow it anyway, it works like a charm.

**Comment by Webbeh** [comment]
Ah yeah, no, it's not built for shadowing, as it requires Bukkit to register events.
Thanks for the feedback, and sorry for the delay.

**Comment by ofirtim** [comment]
I'll tell you what, you can shadowjar it excluding the main class.
You must register the session handler, as you use it in your main class,
I did the same it and worked for me as perfect.

**Comment by Webbeh** [comment]
Let's just say "don't shadow it" to avoid any more confusion with other people.

I'm surprised you can get Bukkit to register events on a plugin that's not loaded by its pluginmanager. Guess you're just doing its job manually instead.
Be wary that `/reload`ing the server after that might just completely break. I suggest you don't shade the jar in your plugin, but drop it in the plugins folder. It's gonna be much easier to maintain for you as well. But it's really up to you.
