### ISSUE TITLE
isPlayerIn APIs throw unexpected exception

### ISSUE THREAD

**Issue by SydMontague** [Webbeh/WorldGuard-Events#8]
Both `isPlayerInAnyRegion` and `isPlayerInAllRegions` throw an IllegalArgumentsException when the player is in no region at all with the message `You need to check for at least one region !`.

The problem is twofold, on one hand it clearly checks the wrong set for emptiness, since players being in no region at all is definitely a valid state. But on the other I think the exception itself is unnecessary, since they can be replaced easily with sensible defaults.

`isPlayerInAnyRegion` -> false, since you can't be in any of none regions
`isPlayerInAllRegions` -> true, since you're always in all of none regions

#7 addresses this issue, but doesn't use the same defaults and still throws exceptions on empty inputs.

**Comment by KingOfMyGames** [comment]
This issue is still not fixed. I just encountered it too and was about to make an issue of it but the issue has already been made half a year ago it seems. Is this project still being maintained?

**Comment by Webbeh** [comment]
Closed with https://github.com/Webbeh/WorldGuard-Events/commit/81bd709a00e64a717ea049926fe62bdd0bf1ebb7.

Project updated on SpigotMC and thoroughly tested on 1.18.1.

**Comment by Webbeh** [comment]
> `isPlayerInAnyRegion` -> false, since you can't be in any of none regions
> `isPlayerInAllRegions` -> true, since you're always in all of none regions

Those checks won't need to happen since there's the exception stopping the function before those checks if the regions to check is empty.

**Comment by SydMontague** [comment]
> > `isPlayerInAnyRegion` -> false, since you can't be in any of none regions
> > `isPlayerInAllRegions` -> true, since you're always in all of none regions
> 
> Those checks won't need to happen since there's the exception stopping the function before those checks if the regions to check is empty.

My point is that the exception shouldn't be thrown to begin with. A player can't be in any given region if no region is given just as a player is always in all given regions if none is given.

**Comment by Webbeh** [comment]
It's just a design choice. It's an illegal argument exception. A null/empty region is... Illegal. I see nothing wrong here.

You're not supposed to check for the presence of a player in a null region. Hence, exception.

**Comment by SydMontague** [comment]
An empty set is not the same as null. In fact, your code will still throw a NullPointerException when passing null.

And checking whether an arbitrary set contains any/every element of an empty set is mathematically valid.
The empty set is a subset of every set, there is no intersection between any set and the empty set.

Just remove the isEmpty checks (or convert them to null checks) and the code will still work mathematically correct without requiring the API user to check the sets for emptiness first.

**Comment by Webbeh** [comment]
I don't really care that any of that is true. In this context, it just doesn't make sense.

Now, if you're asking for a way to check if a player is in no region at all, you can do it with the `WorldGuardEvents.getRegions(uuid)` call, and check for emptiness of its result.

Or use the WorldGuard API directly.
